name: gpt2-enhanced
block_size: 1024
vocab_size: 50304
n_layer: 12
n_head: 12
n_kv_head: 1
n_embd: 768
dropout: 0.0
bias: True
use_rope: True
use_kvcache: False
use_rmsnorm: True
use_gqa: True
use_swiglu: False
hidden_dim: 2048
base: 10000
p: -1
eps: 1.0e-08